// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD93zD7w0dFjm3jKjBSP27yMAkT3kZPUZg',
    appId: '1:89709601859:web:36ff1cc9213baff39020f6',
    messagingSenderId: '89709601859',
    projectId: 'autoyard-437c8',
    authDomain: 'autoyard-437c8.firebaseapp.com',
    storageBucket: 'autoyard-437c8.firebasestorage.app',
    measurementId: 'G-BHPLDVLGR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Z4yvp5OTUuY9WJLmyNkrTuzyo_Kc5n8',
    appId: '1:89709601859:android:fe0fd85293078bee9020f6',
    messagingSenderId: '89709601859',
    projectId: 'autoyard-437c8',
    storageBucket: 'autoyard-437c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKWGg2j7k3AI7tAbsKWTS7AWXispXJM6c',
    appId: '1:89709601859:ios:adf2b546b0ecacfc9020f6',
    messagingSenderId: '89709601859',
    projectId: 'autoyard-437c8',
    storageBucket: 'autoyard-437c8.firebasestorage.app',
    iosBundleId: 'com.autoyard.technology.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKWGg2j7k3AI7tAbsKWTS7AWXispXJM6c',
    appId: '1:89709601859:ios:adf2b546b0ecacfc9020f6',
    messagingSenderId: '89709601859',
    projectId: 'autoyard-437c8',
    storageBucket: 'autoyard-437c8.firebasestorage.app',
    iosBundleId: 'com.autoyard.technology.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD93zD7w0dFjm3jKjBSP27yMAkT3kZPUZg',
    appId: '1:89709601859:web:276c441e9743fb079020f6',
    messagingSenderId: '89709601859',
    projectId: 'autoyard-437c8',
    authDomain: 'autoyard-437c8.firebaseapp.com',
    storageBucket: 'autoyard-437c8.firebasestorage.app',
    measurementId: 'G-DKK83M630M',
  );

}